#undef SUFFIX
#undef DATA_TYPE
#undef DATA_TYPE_S
#undef REG
#undef REG_NAME
#undef MEM_R
#undef MEM_W
#undef MSB
#undef EX_I
#undef PF_check
#undef OF_check
#undef SF_check
#undef ZF_check
#undef MLSB
#undef ADDR